### ISSUE TITLE
The charts should deploy Lighthouse by default

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-charts#101]
**What happened**:

e2e tests now fail because Lighthouse isn’t running.

**What you expected to happen**:

e2e should pass.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy Submariner with the charts, run e2e.

**Comment by nyechiel** [comment]
Hi @skitt - with all the latest submariner-operator Helm chart changes, is this one still relevant?

**Comment by skitt** [comment]
Now that we rely on the operator-based Helm chart, this is handled by the operator.
