### ISSUE TITLE
Use the Operator to create the Broker, not the submariner-k8s-broker chart

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-charts#134]
**What would you like to be added**:

Use `submariner-operator` to deploy the broker, and remove the `submariner-k8s-broker` chart.

This was noted as future work by @skitt in his PR to remove the `submariner` chart: https://github.com/submariner-io/submariner-charts/pull/131#issue-603934328

**Why is this needed**:

To unify the deployment pipeline and avoid duplication/bugs.

I suspect this as a possible root cause of the current Helm E2E failures showing up in the [Lighthouse Flake Finder](https://github.com/submariner-io/lighthouse/actions/workflows/flake_finder.yml).

**Comment by tpantelis** [comment]
bump

**Comment by sridhargaddam** [comment]
@Jaanki are you looking into this use-case?

**Comment by dfarrell07** [comment]
The operator now handles creating the broker, the charts can be updated to use that.

**Comment by nyechiel** [comment]
@dfarrell07 are you looking into this for 0.12?

**Comment by dfarrell07** [comment]
We aren't prioritizing work on the charts, so I think it's okay to close this for now. If we get someone with cycles to focus here, we can revisit.
