### ISSUE TITLE
broker.insecure in helm-chart not working as expected

### ISSUE THREAD

**Issue by Hitesh-Agrawal** [submariner-io/submariner-charts#185]
**What happened**: Trying to use submariner v 0.11.0 with helm deployment with broker.insecure

**What you expected to happen**:
The clusters are unable to register the endpoints in the broker if we use broker url as https://mybroker.server.local:6443/ , using ip https://x.x.x.x:6443/ address works as expected.

**How to reproduce it (as minimally and precisely as possible)**: Try using a insecure broker with name instead of ip and you will get below error
E1116 06:28:03.515256       1 queue.go:104] local -> broker for *v1.Cluster: Failed to process object with key "submariner-operator/ew2": error retrieving "ew2": Get "https://mybroker.server.local:6443/apis/submariner.io/v1/namespaces/submariner-k8s-broker/clusters/ew2": x509: certificate is valid for localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, not mybroker.server.local

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration: AWS
- Install tools:
- Network plugin and version (if this is a network-related bug): vxlan driver
- Others:

**Comment by Hitesh-Agrawal** [comment]
Any update on this , we are blocked due to this. We have 3 rancher masters and hence don't want to point the broker to single ip , but to the ELB which will distribute the load to any of the servers available behind it.

**Comment by skitt** [comment]
I’m working on it; there’s no quick workaround but the fix shouldn’t take too long.

**Comment by Hitesh-Agrawal** [comment]
@skitt I tried today with the 0.12.0-m0 but it didn't work . Did we implement the corresponding change in the helm-chart too.

**Comment by skitt** [comment]
No, the fix isn’t yet implemented in the chart. When it is, this bug will be closed, so you’ll know about it.

**Comment by m4ce** [comment]
@skitt - I think the https://github.com/submariner-io/submariner-charts/blob/devel/submariner-operator/templates/submariner.yaml is missing the option though now that 0.12 supports it?

**Comment by m4ce** [comment]
Oh sorry - just saw your commit here https://github.com/submariner-io/submariner-charts/pull/188 :+1:

**Comment by Hitesh-Agrawal** [comment]
@skitt @tpantelis @sridhargaddam How do I test this change what version of submariner operator charts ( helm repo to use) and the image version should I use.
Will this image work
+        "gateway.image.tag" = "0.12.0-m0"
+        "operator.image.tag" = "0.12.0-m0"
+        "submariner.images.tag" = "0.12.0-m0"
Cheers
Hitesh

**Comment by skitt** [comment]
This should now work, using devel images for everything.
