### ISSUE TITLE
submariner-k8s-broker chart  repo is out of date

### ISSUE THREAD

**Issue by lmxia** [submariner-io/submariner-charts#262]
**What happened**:

I followed [the helm install link](https://submariner.io/operations/deployment/helm/ ) , to install `broker` with `helm`. But found the repo version is 0.12.2. Which the repo contains no secret in format:`{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='${BROKER_NS}-client')]` , so SUBMARINER_BROKER_TOKEN will be  "". 

**What you expected to happen**:
Work as  [described.](https://submariner.io/operations/deployment/helm/ )

**Comment by dfarrell07** [comment]
Relevant: https://github.com/submariner-io/releases/issues/438

**Comment by dfarrell07** [comment]
This is what needs to be done, if we're doing it manually: https://github.com/submariner-io/submariner-charts/pull/246/files

**Comment by dfarrell07** [comment]
This is tracked by https://github.com/submariner-io/releases/issues/438, closing here.
