### ISSUE TITLE
Ensure the Helm charts support Libreswan

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-charts#33]
Once Submariner supports Libreswan, we need to ensure the charts allow it to be enabled. (This might be entirely transparent, with the generic support for cable drivers.)

**Comment by nyechiel** [comment]
@skitt @SteveMattar is this one still relevant? how do we test today with Helm?

**Comment by SteveMattar** [comment]
@nyechiel yes, https://github.com/submariner-io/submariner-charts/pull/123
Today we test using shipyard https://github.com/submariner-io/shipyard/blob/3db0dcce0489d9e3f243f12dbba672d817487b12/scripts/shared/lib/deploy_helm#L56

**Comment by mangelajo** [comment]
But is it relevant anymore? there's only libreswan right?

**Comment by mangelajo** [comment]
@skitt can we close this one?
