### ISSUE TITLE
Inconsistent version updates in chart.yaml

### ISSUE THREAD

**Issue by abguptms** [submariner-io/submariner-charts#376]
**What happened**:
The submariner charts are not pointing to correct releases. Is this expected behavior? 

**What you expected to happen**:
Charts to point to expected release versions.

**How to reproduce it (as minimally and precisely as possible)**:
For **release-0.13**, [chart.yaml](https://github.com/submariner-io/submariner-charts/blob/release-0.13/submariner-operator/Chart.yaml) shows chart version **0.10.1**. Expected **0.13.4** from here: https://github.com/submariner-io/submariner-charts/releases

For **release-0.14**, [chart.yaml](https://github.com/submariner-io/submariner-charts/blob/release-0.14/submariner-operator/Chart.yaml) shows chart version **0.14.0-m1**. Expected **0.14.4**

Finally for **release-0.15**, [chart.yaml](https://github.com/submariner-io/submariner-charts/blob/release-0.15/submariner-operator/Chart.yaml) shows chart version **0.0.0**. Expected **0.15.0**

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by t0lya** [comment]
On a related note, when will 0.15.0 be available in submariner-io.github.io/submariner-charts/charts chart repo? When `CHARTS_VERSION` is bumped up here? https://github.com/submariner-io/submariner-charts/pull/295/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L20

**Comment by tpantelis** [comment]
> On a related note, when will 0.15.0 be available in submariner-io.github.io/submariner-charts/charts chart repo? When `CHARTS_VERSION` is bumped up here? https://github.com/submariner-io/submariner-charts/pull/295/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L20

https://github.com/submariner-io/submariner-charts/pull/377

**Comment by tpantelis** [comment]
> Finally for release-0.15, [chart.yaml](https://github.com/submariner-io/submariner-charts/blob/release-0.15/submariner-operator/Chart.yaml) shows chart version 0.0.0. Expected 0.15.0

The chart version is now specified in the [Makefile](https://github.com/submariner-io/submariner-charts/blob/1426dcadcb13bce5cd99d05e9fdc60e1310ea9a3/Makefile#L20)

**Comment by dfarrell07** [comment]
It looks like there's some updated to Globalnet needed, see discussion on #377.

**Comment by dfarrell07** [comment]
We're working on a permanent fix for bumping the chart versions during releases here: https://github.com/submariner-io/releases/pull/726
