### ISSUE TITLE
Cannot disable Connectivity component/gateway controller through Helm chart

### ISSUE THREAD

**Issue by t0lya** [submariner-io/submariner-charts#378]
**What happened**:
We have submariner-operator Helm chart installed in our cluster (using process outlined in https://submariner.io/operations/deployment/helm/).

We are running into lighthouse-coredns issue reported in https://github.com/submariner-io/lighthouse/issues/936, where clusterset.local DNS resolutions are failing because of gateway controller. We do not require gateway controller, as we only use the Service Discovery component of Submariner.

Fix https://github.com/submariner-io/lighthouse/pull/1086 was rolled out to check for `Submariner` resource before enabling gateway controller. This fix works for the `subctl` installation flow. But Helm installation flow requires `Submariner` resource. `subctl` with Service Discovery component only uses `ServiceDiscovery` resource to deploy operator (https://github.com/submariner-io/subctl/blob/a86c03b457a9addb456ecd09d550f27839c70933/pkg/deploy/servicediscovery.go#L45). But this resource is not currently supported by the Helm chart.

**What you expected to happen**:

We expect to be able to use Submariner in Service Discovery mode only and be able to disable gateway controller when installing Submariner using Helm.

As manual mitigation, we are deleting `gateways.submariner.io` CRD in our clusters. But the CRD gets reinstalled every time submariner-operator pod restarts. We would like a proper way to disable the gateway controller.

**How to reproduce it (as minimally and precisely as possible)**:

1. Follow https://submariner.io/operations/deployment/helm/ to install submariner-operator on cluster
2. Follow https://submariner.io/operations/usage/  to deploy and export nginx-test Service
3. `nslookup nginx.nginx-test.svc.clusterset.local` should fail

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools: Helm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dfarrell07** [comment]
Thanks for the report @t0lya! Our current devs aren't able to prioritize Helm over subctl deployments, but we're happy to welcome contributions from folks that want to use Helm.
