### ISSUE TITLE
Add helm/chart-testing linting/testing

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-charts#68]
Run the "official" Helm linter/tester against our Helm charts.

https://github.com/helm/chart-testing-action

**Comment by dfarrell07** [comment]
I still think we should do this.

**Comment by skitt** [comment]
We still want this.

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
This seems like a nice, relevant guide: https://redhat-cop.github.io/ci/linting-testing-helm-charts.html
