### ISSUE TITLE
Add helm-docs automatic docs generation/testing

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/submariner-charts#69]
Use helm-docs to auto-generate docs for our Helm charts.

https://github.com/norwoodj/helm-docs

Verify that docs are always up-to-date in CI.

https://dev.to/jamiemagee/how-to-host-your-helm-chart-repository-on-github-3kd

**Comment by dfarrell07** [comment]
I still think we should do this.

**Comment by skitt** [comment]
We still want this.

**Comment by tpantelis** [comment]
bump
