### ISSUE TITLE
The charts web site isn’t getting updated

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-charts#78]
https://submariner-io.github.io/submariner-charts/charts is supposed to be updated every time a pull request is merged; the Travis job runs successfully, and the `gh-pages` branch is updated, but the web site isn’t updated. (See https://submariner-io.github.io/submariner-charts/charts/index.yaml and check against the version in https://github.com/submariner-io/submariner-charts/blob/gh-pages/charts/index.yaml).

**Comment by mangelajo** [comment]
According to stackoverflow tribal knowledge, it seems that... once you are using a custom domain, also the subproject pages need a CNAME file:

https://github.com/submariner-io/submariner-charts/blob/gh-pages/CNAME

**Comment by mangelajo** [comment]
I
